### ISSUE TITLE
Cant install in Atom

### ISSUE THREAD

**Issue by bgarrant** [rainglow/atom#3]
This is not installing in Atom.  I just get this error:

```
Installing rainglow-atom to /Users/bgarrant/.atom/packages ✗
No releases available for rainglow-atom
```

**Comment by estebancastro** [comment]
@bgarrant same here "No releases available for rainglow-atom"
[atom v1.23.3](https://github.com/atom/atom/releases/tag/v1.23.3)

**Comment by bgarrant** [comment]
Something is not setup right in the repo it seems

**Comment by mostafa6765** [comment]
@bgarrant install manually .
 Clone the repository and rename `rainglow-atom` copy paste into ~/.atom/packages. Now restart the editor.

* apm install issue resolve as soon as.

**Comment by bgarrant** [comment]
That gets it install but ever color change requires a reboot of Atom

**Comment by daylerees** [comment]
Hi @bgarrant, I was having some troubles publishing the package. It's now available as 'rainglow' for install within the editor. Sorry about that!

Unfortunately, the way the switcher works demands a restart of the editor when changing themes. It's because Atom's package format doesn't support multiple themes by default, so we have needed to write a temp theme file, and the restart has to happen to pickup the changes. (Or alternatively, change the theme Rainglow to another, and then back again.) Thanks for the report!

**Comment by bgarrant** [comment]
Love these themes Dayle.  Works great in Atom now.
